apiVersion: v1
data:
  s3-backup.yml: |
    s3_backup:
      debug: {{ .Values.s3_backup.config.debug | quote }}
      stopOnFailure: {{ .Values.s3_backup.config.stopOnFailure | quote }}
      {{- with .Values.s3_backup.config.sources }}
      sources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.s3_backup.config.remotes }}
      remotes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.s3_backup.config.backups }}
      backups:
        {{- toYaml . | nindent 8 }}
      {{- end }}

kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "s3_backup.fullname" . }}-config

